# Site settings
title: Portfólio de análises
email: enio.abrantes.silva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Análises interessantes sobre os mais diversos assuntos.

baseurl: "/portfolio-analises" # the subpath of your site, e.g. /blog/
url: "https://enioabrantes.github.io/portfolio-analises/" # the base hostname & protocol for your site
github_username:  EnioAbrantes
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
