# Site settings
title: Portfólio de análises
email: enio.abrantes.silva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Análises interessantes sobre os mais diversos assuntos.
url: "http://analiseminhanalise.com" # the base hostname & protocol for your site
twitter_username:
github_username:  EnioAbrantes
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
